package hayden.applogger;

enum StepType {

	REQUEST_TRANSACTION,
	VALIDATION_TRANSACTION,
	START_TRANSACTION,
	AUTHORIZE_PAYMENT,
	CAPTURE_PAYMENT,
	CANCEL_PAYMENT,
	REFUND_PAYMENT,
	AUTHORIZE_RECHARGE,
	CONFIRM_RECHARGE,
	CANCEL_RECHARGE

}
